### PR TITLE
ConduitError and SessionTaskResponse

### PR DESCRIPTION
**Pull request by eneko**
- [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines*](https://github.com/mindbody/conduit/blob/master/CONTRIBUTING.md).

This pull request includes (pick all that apply):

- [ ] Bugfixes
- [x] New features
- [x] Breaking changes
- [ ] Documentation updates
- [x] Unit tests
- [ ] Other

### Summary
This pull request covers three major points in regards of error handling and request responses.
- Simplifies error handling by condensing all error types into `ConduitError`.
- Adds support for `LocalizedError` protocol, for a much improved debugging/logging experience.
- Condenses response tuples `(data, response, error)` into a single, easier to handle, `SessionTaskResponse` structure.

#### `ConduitError`
At the moment, error handling in Conduit is good _enough_, but it can be improved and simplified. There is a long list of error types that Conduit can return, which can make it hard for consuming applications to do pattern matching.

`OAuth2Error`, `DataConversionError`, `RequestSerializerError`, `ResponseDeserializerError`, `XMLError`, `URLError`, `URLSessionClientError`, are all now returned as `ConduitError` with proper associated values, or informative error messages.

#### `LocalizedError`
By having `ConduitError` conform to the `LocalizedError` protocol, we can get descriptive error messages while debugging the application, or on application log output. Most importantly, we can get useful error messages printed out to the log when unit or integration test fail.

For unit and integration tests, this can be easily achieved by passing the error to `XCTFail` as `XCTFail(error.localizedDescription)` or by having a test method `throw`. In both cases, `XCTest` will print useful information about the error, provided by Conduit.

Before:
> Conduit.RequestSerializerError error 1.

Now:
> Conduit Internal Error: Unnaceptable Mime type: text/html

#### `SessionTaskResponse`
When working with network requests, more than often, Conduit logic has to pass around information regarding `Data`, `HTTPURLResponse` and `Error`. This is often passed returned or passed around as a tuple of two or three elements. If we were to need the original `URLRequest` object, this tuple could now have four elements. While this technique works, it adds noise polluting the code.

There was already an instance where Conduit stored this information in a `TaskResponse` structure, used for progressive downloads. This pull request takes advantage of this type and, while renaming it to `SessionTaskResponse`, uses it in all scenarios where the `(data, response, error)` tuple was previously used. 

By doing this, we remove boilerplate and simplify the code.

For consuming applications/frameworks, calls like:
```
client.begin(request: request) { (data, response, error) in
    if let error = error {
        ...
}
```

Will become:
```
client.begin(request: request) { taskResponse in
    if let error = taskResponse.error {
        ...
}
```

### Implementation
- `ConduitError` was put together by removing all other `Error` types, while maintaining any relevant error cases. Error cases that were not widely used (eg. `XMLError.notFound`) were replaced with an `internalError` given a descriptive error message, and are no longer available.
- `LocalizedError` was implemented to provide descriptive error messages for each supported error case.
- `SessionTaskResponse` did already exist as `TaskResponse`. It was minimally refactored, and renamed. It is now used instead of the tuple `(data, response, error)`.

### Test Plan
There is no logic or behavior changes in this pull request. Conduit should work exactly as it did before. However, the interface for `URLSessionClient` requests, and for error pattern matching, will have to be updated by consuming applications/frameworks.

Unit tests have been added for `ConduitError` to test pattern matching and debug descriptions.

### CODE REVIEW

**Comment by rminus** [comment]
### SwiftLint found issues

#### Warnings

File | Line | Reason |
| --- | ----- | ----- |
ProtectedResourceService.swift | 14 | Force unwrapping should be avoided. 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by johnhammerlund** [comment]
Still open to these concepts as a v2 implementation. Consolidation of types will make Conduit far more usable and extendable.

**Comment by eneko** [comment]
@johnhammerlund sounds good. Let me know when do you think v2 would happen, I can work on updating this branch and resolving the conflicts.

**Comment by eneko** [comment]
Closed in favor of new roadmap.

**Pull request closed without merging**
