### PR TITLE
(Bugfix Issue 137) | Crash in URLSessionClient

### PR DESCRIPTION
**Pull request by brettwellmanmbo**
- [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines*](https://github.com/mindbody/conduit/blob/master/CONTRIBUTING.md).

This pull request includes (pick all that apply):

- [x] Bugfixes
- [ ] New features
- [ ] Breaking changes
- [ ] Documentation updates
- [ ] Unit tests
- [ ] Other

### Summary
- A crash can sometimes occur in URLSessionClient
- https://github.com/mindbody/Conduit/issues/137

### Implementation
Moved dictionary indexing for a completion block collection to the an existing serial queue to avoid edge-case crashes

### Test Plan
Utilize the framework

### CODE REVIEW

**Comment by rminus** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Source files were modified – don’t forget to update the CHANGELOG if there are code changes.<br />
You can find examples within the <a href="https://github.com/mindbody/Conduit/blob/master/CHANGELOG.md">CHANGELOG.md</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by johnhammerlund** [comment]
Looks good :+1: but SwiftLint appears to be throwing a false-positive. I'll check it out

**Comment by johnhammerlund** [comment]
Looks like there is an open issue: https://github.com/realm/SwiftLint/issues/2782

We might need to set up a workaround for the time being. I'll open a separate PR to remediate.

**Comment by johnhammerlund** [comment]
https://github.com/mindbody/Conduit/pull/139

**Comment by eneko** [comment]
Need to update the CHANGELOG and prep a release

**Pull request merged**
