### PR TITLE
(Bugfix)|Add SwiftLint exception to clear false-positive (duplicate_enum_case)

### PR DESCRIPTION
**Pull request by johnhammerlund**
- [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines*](https://github.com/mindbody/conduit/blob/master/CONTRIBUTING.md).

This pull request includes (pick all that apply):

- [x] Bugfixes
- [ ] New features
- [ ] Breaking changes
- [ ] Documentation updates
- [ ] Unit tests
- [ ] Other

### Summary
A recent release of SwiftLint includes a new implicit rule, `duplicate_enum_cases`. This rule doesn't consider conditional compilation flags, as described in the open issue here: https://github.com/realm/SwiftLint/issues/2782

For now, I've added an exception to allow builds to proceed.

### Implementation
Added a SwiftLint exception surrounding the false-positive in `MultipartFormRequestSerializer.swift`

### Test Plan
Build should pass with the latest version of SwiftLint installed

### CODE REVIEW

**Comment by eneko** [comment]
This works. We also have an `Image` type alias that we should be using, instead of `#if/else`

**Comment by eneko** [comment]
Could you set the base branch to `bugfix/PS-8953-crash-in-urlsessionclient`?

**Comment by johnhammerlund** [comment]
@eneko might as well, yeah, I can do that.

**Comment by rminus** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Source files were modified – don’t forget to update the CHANGELOG if there are code changes.<br />
You can find examples within the <a href="https://github.com/mindbody/Conduit/blob/master/CHANGELOG.md">CHANGELOG.md</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
